# Generated by Django 5.1.1 on 2025-12-10 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='parkinghistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Parking History', 'verbose_name_plural': 'Parking Histories'},
        ),
        migrations.AlterModelOptions(
            name='parkingslot',
            options={'ordering': ['slot_number'], 'verbose_name': 'Parking Slot', 'verbose_name_plural': 'Parking Slots'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-entry_time'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Activity Log', 'verbose_name_plural': 'User Activity Logs'},
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='max_parallel_bookings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='parkinghistory',
            index=models.Index(fields=['vehicle_number'], name='app_parking_vehicle_977860_idx'),
        ),
        migrations.AddIndex(
            model_name='parkinghistory',
            index=models.Index(fields=['timestamp'], name='app_parking_timesta_7514f4_idx'),
        ),
    ]
