# Generated by Django 5.1.1 on 2025-12-14 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_update_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='membership',
        ),
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveConstraint(
            model_name='usermembership',
            name='unique_user_membership',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_free_booking',
        ),
        migrations.RemoveField(
            model_name='economicsreport',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='daily_free_parking_limit',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='max_parallel_bookings',
        ),
        migrations.RemoveField(
            model_name='parkinghistory',
            name='is_free_parking',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_free_parking',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='free_parking_used_today',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='last_reset_date',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='total_parking_used',
        ),
        migrations.AddField(
            model_name='economicsreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='free_entries_used_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='last_free_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.parkingslot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='economicsreport',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('digital', 'Digital Payment'), ('card', 'Card')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='economicsreport',
            name='transaction_type',
            field=models.CharField(choices=[('entry_fee', 'Entry Fee'), ('booking_fee', 'Booking Fee'), ('other', 'Other')], default='entry_fee', max_length=20),
        ),
        migrations.AlterField(
            model_name='economicsreport',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='ip_address',
            field=models.CharField(blank=True, default='exit', max_length=45),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubscriptionPayment',
        ),
    ]
