# Generated by Django 5.1.1 on 2025-12-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_subscriptionpayment_membership_and_more'),
    ]

    operations = []


